export const data = [
  {
    id: '1',
    title: 'Similar post to this! Lorem, ipsum 1.',
    date: '25.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '2',
    title: 'Similar post to this! Lorem, ipsum 2.',
    date: '26.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '3',
    title: 'Similar post to this! Lorem, ipsum 3.',
    date: '26.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '3',
    title: 'Similar post to this! Lorem, ipsum 4.',
    date: '26.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '4',
    title: 'Similar post to this! Lorem, ipsum 5.',
    date: '26.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '5',
    title: 'Similar post to this! Lorem, ipsum 6.',
    date: '26.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'article',
  },
  {
    id: '6',
    title: 'Similar post to this! Lorem, ipsum 8.',
    date: '27.11.2020',
    tags: ['it', 'digital', 'react'],
    postCategory: 'project',
  },
];
